### ISSUE TITLE
Pre-roll not being made

### ISSUE THREAD

**Issue by justinglock40** [AndrewHolmes060/Plex-Preroll-Builder#10]
So getting the POST Messages now, but looking at HTOP. I don't see anywhere, where ffmpeg is doing any work and there's no files in /prerolls folder.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/23133649/120926468-045f6500-c6ab-11eb-8d39-660c1511fb35.png">

**Comment by justinglock40** [comment]
So looks like the script is expecting `/overlays`, but the folder when pulled from git is `/Overlays`.

Additionally, the overlays it's looking for is missing? 

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/23133649/120927258-42aa5380-c6ae-11eb-905a-accb95ddaa93.png">

**Comment by justinglock40** [comment]
Do you have the `prerolloverlay.mov`?

**Comment by HolmesBrew** [comment]
The prerolloverlay has been added and it should now be fully functional. apologies ive been away from github for quite a while.
