### ISSUE TITLE
CV2 Install Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by doob187** [AndrewHolmes060/Plex-Preroll-Builder#2]
```
 sudo pip3 install cv2
```
ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2

**Comment by irodimus** [comment]
I used opencv-python and that appears to work.

```
sudo pip3 install opencv-python
```

**Comment by doob187** [comment]
> I used opencv-python and that appears to work.
> 
> ```
> sudo pip3 install opencv-python
> ```

See my PR but he closed it 

https://github.com/AndrewHolmes060/Plex-Preroll-Builder/pull/1

**Comment by HolmesBrew** [comment]
hey sorry havent looked at this project for ages but your totally right ive made the changes as well as changed a large chunk of the script to support webhooks etc.

Thanks
